name = "MethodOfLines"
uuid = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
authors = ["Alex Jones, <alex.lemony@gmail.com>"]
version = "0.6.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "1"
DiffEqBase = "6"
DomainSets = "0.5"
IfElse = "0.1"
Interpolations = "0.14"
Latexify = "0.15"
ModelingToolkit = "8.22"
NonlinearSolve = "0.3, 1"
OrdinaryDiffEq = "6"
SafeTestsets = "0.0.1"
SciMLBase = "1.57"
StableRNGs = "1"
StaticArrays = "1"
SymbolicUtils = "0.19"
Symbolics = "4"
TermInterface = "0.2, 0.3"
julia = "1.6"
